export const API_ROOT = "http://192.168.8.1:4321"
export const HEALTH = "health"
export const BROADCAST = "broadcast"
export const START = "start"
export const STOP = "stop"
export const STATUS = "status"